# Generated by Django 6.0.5 on 2026-05-17 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Flight Class',
                'verbose_name_plural': 'Flight Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('zero', 'Non-stop'), ('one', '1 Stop'), ('two_or_more', '2+ Stops')], max_length=20, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stop Type',
                'verbose_name_plural': 'Stop Types',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('days_left', models.PositiveIntegerField()),
                ('predicted_price', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.airline')),
                ('destination_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pred_arrivals', to='predictor.city')),
                ('flight_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.flightclass')),
                ('source_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pred_departures', to='predictor.city')),
                ('stops', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.stoptype')),
                ('arrival_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pred_arrivals', to='predictor.timeslot')),
                ('departure_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pred_departures', to='predictor.timeslot')),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('days_left', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='predictor.airline')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='predictor.city')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='predictor.flightclass')),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='predictor.city')),
                ('stops', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='predictor.stoptype')),
                ('arrival_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='predictor.timeslot')),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='predictor.timeslot')),
            ],
            options={
                'verbose_name': 'Flight Record',
                'verbose_name_plural': 'Flight Records',
                'indexes': [models.Index(fields=['airline'], name='predictor_f_airline_589d63_idx'), models.Index(fields=['source_city', 'destination_city'], name='predictor_f_source__8a3538_idx'), models.Index(fields=['flight_class'], name='predictor_f_flight__8517d7_idx'), models.Index(fields=['price'], name='predictor_f_price_7026a8_idx')],
            },
        ),
    ]
